server:
  port: 8080
spring:
  redis:
    host: k8a809.p.ssafy.io
    port: 6379
    password: <redis-password>
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://k8a809.p.ssafy.io:3306/<db-name>?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: <mysql-password>
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 100